import json, sys
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen

TTF = "/Users/david/Documents/otzaria-software/otzaria/build/macos/Build/Products/Debug/App.framework/Versions/A/Resources/flutter_assets/packages/fluentui_system_icons/fonts/FluentSystemIcons-Regular.ttf"

# שם לוגי בתוסף -> שם אייקון FluentUI -> codepoint (מתוך fluent_icon_resolver.dart)
ICONS = {
    "settings": 63146,
    "download": 61777,
    "mail": 62727,
    "sync": 61841,
    "open": 62851,
    "bold": 63397,
    "italic": 63477,
    "underline": 63499,
    "list-ordered": 63482,
    "list-bullet": 60634,
    "undo": 61850,
    "redo": 61807,
    "clear-format": 63421,
    "chevron-down": 62116,
    "chevron-up": 62135,
    "book-open": 57721,
    "document": 62329,
    "search": 63120,
    "edit": 62430,
    "filter": 62471,
    "info": 62628,
    "dismiss": 62314,
    "font": 63461,
    "alert": 61717,
    "calendar": 57935,
    "clock": 62174,
}

font = TTFont(TTF)
gs = font.getGlyphSet()
cmap = font.getBestCmap()
em = font["head"].unitsPerEm
out = {}
for name, cp in ICONS.items():
    gname = cmap.get(cp)
    if not gname:
        print("MISSING", name, cp, file=sys.stderr); continue
    pen = SVGPathPen(gs)
    gs[gname].draw(pen)
    out[name] = pen.getCommands()

ts = "// GENERATED by scripts/extract-icons.py — אל תערוך ידנית.\n"
ts += "// אייקוני FluentUI System Icons (אותו סט שאוצריא משתמשת בו), חולצו מ-FluentSystemIcons-Regular.ttf.\n"
ts += f"export const ICON_EM = {em};\n"
ts += "export const ICON_PATHS: Record<string, string> = {\n"
for name, d in out.items():
    ts += f"  {json.dumps(name)}: {json.dumps(d)},\n"
ts += "};\n"
ts += "export type IconName = keyof typeof ICON_PATHS;\n"
open("src/icons/fluent.ts", "w").write(ts)
print(f"✓ {len(out)} icons → src/icons/fluent.ts (em={em})")
